### ISSUE TITLE
java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by mckite** [megoesrawr/Modern-LWC#115]
**LWC Version (/lwc admin version):** 

2.0.8
**Server version (/version):** 

1.12.2

[20:43:13 INFO]: This server is running CraftBukkit version git-Spigot-642f6d2-6103339 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[20:43:13 INFO]: Checking version, please wait...
[20:43:13 INFO]: You are 162 version(s) behind

**Short five word summary of issue:** 

No Method Error Due to no item method in 1.13 is not in lower version.

**Detailed description of problem:**

[20:40:29 ERROR]: Could not pass event PlayerInteractEvent to LWC v2.0.8
org.bukkit.event.EventException: null
        at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:79) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoSuchFieldError: LEGACY_REDSTONE_TORCH_OFF
        at com.griefcraft.util.ProtectionFinder.tryLoadProtection(ProtectionFinder.java:284) ~[?:?]
        at com.griefcraft.util.ProtectionFinder.matchBlocks(ProtectionFinder.java:117) ~[?:?]
        at com.griefcraft.lwc.LWC.findProtection(LWC.java:1250) ~[?:?]
        at com.griefcraft.lwc.LWC.findProtection(LWC.java:1223) ~[?:?]
        at com.griefcraft.listeners.LWCProtocoLib.onPlayerInteract(LWCProtocoLib.java:31) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:69) ~[?:?]
        ... 17 more

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by megoesrawr** [comment]
2.0.8 is for 1.13 only for now.
