### ISSUE TITLE
players cant use anvil, enchanting_table, enderchest and workbench in protected areas

### ISSUE THREAD

**Issue by palipajo** [megoesrawr/Modern-LWC#118]
**LWC Version (/lwc admin version): Main plugin: 2.0.8/
**Server version (/version): This server is running CraftBukkit version git-Spigot-417cfb3-96778ca (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

worldguard support needed

with worldguard:
          enabled: false
- players cant use anvil, enchanting_table, enderchest and workbench in protected areas

with worldguard:
          enabled: true
- players can use anvil, enchanting_table, enderchest and workbench in protected areas but it spams the console with errors.

**If there was an error in console, put it here:**
[13:15:11] [Server thread/WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.0.8
[13:15:11] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:394)
[13:15:11] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.canAccessProtection(LWC.java:801)
[13:15:11] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:664)
[13:15:11] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:15:11] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:15:11] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:15:11] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:15:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[13:15:11] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:15:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[13:15:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[13:15:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238)
[13:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:452)
[13:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227)
[13:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[13:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[13:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10)
[13:15:11] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:15:11] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[13:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198)
[13:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884)
[13:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[13:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[13:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[13:15:11] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:15:11] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionContainer()Lcom/sk89q/worldguard/bukkit/RegionContainer;
[13:15:11] [Server thread/WARN]: 	at com.griefcraft.modules.pluginsupport.WorldGuard.onAccessRequest(WorldGuard.java:246)
[13:15:11] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:368)
[13:15:11] [Server thread/WARN]: 	... 24 more
[13:15:14] [Server thread/ERROR]: [LWC] Unhandled exception occured in onPacketSending(PacketEvent) for LWC
com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.0.8
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:394) ~[?:?]
	at com.griefcraft.lwc.LWC.canAccessProtection(LWC.java:801) ~[?:?]
	at com.griefcraft.lwc.LWC.canAccessProtection(LWC.java:345) ~[?:?]
	at com.griefcraft.listeners.LWCProtocoLib$1.onPacketSending(LWCProtocoLib.java:40) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_13_R1.NetworkManager.b(NetworkManager.java:194) ~[spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.NetworkManager.sendPacket(NetworkManager.java:158) ~[spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1384) ~[spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.PlayerConnection.sendPacket(PlayerConnection.java:1357) ~[spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.EntityPlayer.openTileEntity(EntityPlayer.java:792) ~[spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.BlockAnvil.interact(SourceFile:70) ~[spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.IBlockData.interact(SourceFile:281) ~[spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) ~[spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-417cfb3-96778ca]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionContainer()Lcom/sk89q/worldguard/bukkit/RegionContainer;
	at com.griefcraft.modules.pluginsupport.WorldGuard.onAccessRequest(WorldGuard.java:246) ~[?:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:368) ~[?:?]
	... 35 more
[13:15:14] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_13_R1.PacketPlayOutOpenWindow@4607be2d[
    a=2
    b=minecraft:anvil
    c=TranslatableComponent{key='block.minecraft.anvil', args=[], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
    d=0
    e=0
  ]
<paste it here between the little tick marks>
```

**Comment by Tsuser1** [comment]
Fixed with same solution as #111.

**Issue closed.**
