### ISSUE TITLE
Error in 1.8

### ISSUE THREAD

**Issue by Superdarco** [megoesrawr/Modern-LWC#94]
**LWC Version (/lwc admin version):** 2.0.7
**Server version (/version):** 1.8.8 (1.8.8-R0.1 git-Spigot-21fe707-e1ebe52)

**Short five word summary of issue:** Error on start in 1.8.8

**Detailed description of problem:** Now i tested the plugin in the 1.8.8, And when the plugin starts, this error comes out.

**If there was an error in console, put it here:**
```
[18:11:12] [Server thread/INFO]: [LWC] Enabling LWC v2.0.7
[18:11:12] [Server thread/INFO]: [LWC] Connecting to SQLite
[18:11:13] [Server thread/INFO]: [LWC] Creating index on internal
[18:11:13] [Server thread/INFO]: [LWC] Added Hoppers to Blacklisted Blocks in core.yml (optional.blacklistedBlocks)
[18:11:13] [Server thread/INFO]: [LWC] This means that Hoppers CANNOT be placed around protections a player does not have access to
[18:11:13] [Server thread/INFO]: [LWC] If you DO NOT want this feature, simply remove 154 (Hoppers) from blacklistedBlocks :-)
[18:11:13] [Server thread/INFO]: [LWC] Updating to 1.13 material name system.
[18:11:13] [Server thread/ERROR]: Error occurred while enabling LWC v2.0.7 (Is it up to date?)
com.griefcraft.scripting.ModuleException: java.sql.SQLException: statement is not executing
	at com.griefcraft.sql.Database.printException(Database.java:211) ~[?:?]
	at com.griefcraft.sql.PhysDB.precache(PhysDB.java:906) ~[?:?]
	at com.griefcraft.lwc.LWC.load(LWC.java:1621) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:258) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.sql.SQLException: statement is not executing
	at org.sqlite.Stmt.checkOpen(Stmt.java:49) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.sqlite.PrepStmt.batch(PrepStmt.java:170) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.sqlite.PrepStmt.setInt(PrepStmt.java:197) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at com.griefcraft.sql.PhysDB.precache(PhysDB.java:894) ~[?:?]
	... 10 more
```

**Comment by Tsuser1** [comment]
Corrected formatting. Bug under review.

**Comment by megoesrawr** [comment]
Try this version please. http://jenkins.theemeraldage.com:8080/job/Modern%20LWC/lastSuccessfulBuild/artifact/target/Modern-LWC-2.0.7.jar

**Comment by Superdarco** [comment]
Well, it seems that now it works, but when it starts it tells me that it is version 2.0.1 of the version that says in the file. I hope that works, Greetings and thanks.
