### ISSUE TITLE
Error log when /cprivate

### ISSUE THREAD

**Issue by MetalGearDaner** [megoesrawr/Modern-LWC#98]
**LWC Version (/lwc admin version):** 2.0.7
**Server version (/version):**  CraftBukkit version git-Spigot-2086bb0-21d5f75 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Short five word summary of issue:** Error found on console log, reported by user.

**Detailed description of problem:**
Not much more information, just an error log when the player used /cprivate.

**If there was an error in console, put it here:**
```
[17:52:59 INFO]: MrCosmic issued server command: /cprivate
[17:52:59 INFO]: [LWC] onCommand create
[17:53:00 WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.0.7
[17:53:00 WARN]:        at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:394)
[17:53:00 WARN]:        at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:718)
[17:53:00 WARN]:        at sun.reflect.GeneratedMethodAccessor264.invoke(Unknown Source)
[17:53:00 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:53:00 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:53:00 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[17:53:00 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:53:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[17:53:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[17:53:00 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
[17:53:00 WARN]:        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458)
[17:53:00 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951)
[17:53:00 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[17:53:00 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[17:53:00 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[17:53:00 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:53:00 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:53:00 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[17:53:00 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[17:53:00 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[17:53:00 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[17:53:00 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[17:53:00 WARN]:        at java.lang.Thread.run(Thread.java:748)
[17:53:00 WARN]: Caused by: java.lang.NullPointerException
[17:53:00 WARN]:        at com.griefcraft.lwc.SimpleMessageParser.parseMessage(SimpleMessageParser.java:68)
[17:53:00 WARN]:        at com.griefcraft.lwc.LWC.sendLocale(LWC.java:910)
[17:53:00 WARN]:        at com.griefcraft.modules.create.CreateModule.onProtectionInteract(CreateModule.java:68)
[17:53:00 WARN]:        at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:360)
[17:53:00 WARN]:        ... 22 more

```

**Comment by megoesrawr** [comment]
It seems your language file doesn't have the right message. Try using http://jenkins.theemeraldage.com:8080/job/Modern%20LWC/lastSuccessfulBuild/artifact/target/Modern-LWC-2.0.jar

**Comment by MetalGearDaner** [comment]
Thanks! I'll check out that version.

**Comment by MetalGearDaner** [comment]
Seems to be fixed with the latest version.
